apiVersion: v1
kind: Secret
metadata:
  name: postgre-password-secret
type: Opaque
data: 
  password: MTIzcXdl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab1-6-appsettings
data: 
  value: '{ 
    "UsersDB": "server=postgres-postgresql;port=5432;User Id=Lab1_6_User;password={passwrord_placeholder};database=Lab1_6_Db;"
  }'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bykovd-lab1-6-migration-job
spec:
  template:
    metadata:
      labels:
        app: bykovd-lab1-6-migration-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: bykovd-lab1-6-migration
        image: bykovd1984/softwarearchitect-lab1.6:1.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: lab1-6-appsettings-volume
            mountPath: /app/appsettings.json
            readOnly: true      
            subPath: appsettings.json
        env:
        - name: USERS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-password-secret
              key: password
      volumes:
        - name: lab1-6-appsettings-volume
          configMap: 
            name: lab1-6-appsettings
            items: 
            - key: value
              path: appsettings.json
            
