apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name}}-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name}}
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30123