apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-nodeport
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - name: web
    port: 8081
    targetPort: 8000
    nodePort: 30123
---    
apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql-loadbalancer
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
spec:
  ports:
  - port: 5433
    name: localproxy
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
    role: primary 
  type: LoadBalancer      