secret:
  name: postgre-auth-password-secret
  value: MTIzcXdl

configMap: 
  name: lab1-6-auth-appsettings
  value: '{"ConnectionStrings": {"DefaultConnection": "server=postgres-auth-postgresql;port=5432;User Id=Lab1_6_auth_User;password=123qwe;database=Lab1_6_auth_Db;" }}'

deployment:
  name: bykovd-lab1-6-auth
  image: bykovd1984/softwarearchitect-lab1.6-auth:1.2
