apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name }}-nodeport-ingress
spec:
  rules:
  - host: arch-auth.homework
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.deployment.name }}-nodeport
            port:
              number: 5021     