apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-nodeport
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - name: web
    port: 5021
    targetPort: 5002
    nodePort: 30124