apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-nodeport
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - name: web
    port: 5021
    targetPort: 5002
    nodePort: 30124
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-postgresql-loadbalancer
  labels:
    app.kubernetes.io/instance: postgres-auth
    app.kubernetes.io/name: postgresql
spec:
  ports:
  - port: 5432
    name: localproxy
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: postgres-auth
    app.kubernetes.io/name: postgresql
    role: primary 
  type: LoadBalancer  